services:
  webssh-oidc:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    # image: webssh-oidc
    ports:
      - "8444:8444"
    volumes:
      - ./config:/app/config
    env_file:
      - .env
