services:
  webssh-oidc:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    # image: webssh-oidc
    restart: on-failure
    ports:
      - '8444:8444'
    volumes:
      - ./config:/app/config
      - ./config/docs/:/app/build/client/docs
    # set NODE_ENV to production or development, depending on whether you're running in production with ssl or not
    environment:
      - NODE_ENV=production
    env_file:
      - .env
