services:
  webssh-oidc:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    # image: webssh-oidc
    restart: on-failure
    ports:
      - "8444:8444"
    volumes:
      - ./config:/app/config
      - ./config/docs/:/app/build/client/docs
    env_file:
      - .env
